name: Latest Version Release
on:
  push:
    branches:        
      - main
  workflow_dispatch:
jobs:
  latest-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest