name: Test Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Action
        uses: ./
        with:
          exempt_user_list: "github-actions[bot]"
          exempt_labels: "help wanted"
          token: ${{secrets.GITHUB_TOKEN}}
          label: needs-triage